### ISSUE TITLE
Add-on Fails to Start

### ISSUE THREAD

**Issue by chabad360** [phnix-dev/kenney-assets-godot-plugin#2]
Every time I try to enable the add-on (build is `v4.3.stable.mono.arch_linux`), I get the following error:

```
Unable to load addon script from path: 'res://addons/kenney_assets_helper/scripts/KenneyAssetsPlugin.cs'. This might be due to a code error in that script.
Disabling the addon at 'res://addons/kenney_assets_helper/plugin.cfg' to prevent further errors.
```
There doesn't appear to be anything of relevance in the output logs either.

**Comment by phnix-dev** [comment]
Hello, sorry for the delay. I will fix it as soon as possible! 👍

**Comment by KHSDigiTech** [comment]
still doesn't work. Same error, except it's looking for files in a folder called kenney_assets_viewer, which doesn't exist. Renaming kenney_assets_helper to kenney_assets_viewer also doesn't work

**Comment by phnix-dev** [comment]
@KingsLukeSmith Thanks for the report, I was able to reproduce the problem, it may be because the addon is made with csharp, so the first time you install it, it produces an error. But after building the csharp project and restarting I did not get the error anymore.
Can you try this with the latest source files of the addon?

**Comment by KrisSiegel** [comment]
I have the same error when attempting to enable the plugin. Since the plugin doesn't include an msbuild file, I'm not sure exactly how I should build the plugin in order for it to work as expected in godot.

(Maybe there is a way with godot? I'm new to godot and didn't see anything obvious)

**Comment by KrisSiegel** [comment]
Ah, I see. Doing a `dotnet build` on the entire project, as long as there is at least one C# script, seems to fix _that_ error but next I get
```
  ERROR: Cannot open file 'res://addons/kenney_assets_viewer/dock.tscn'.
  ERROR: Failed loading resource: res://addons/kenney_assets_viewer/dock.tscn. Make sure resources have been imported by opening the project in the editor at least once.
  ERROR: Error loading resource: 'res://addons/kenney_assets_viewer/dock.tscn'.
  ERROR: /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/NativeInterop/ExceptionUtils.cs:113 - System.NullReferenceException: Object reference not set to an instance of an object.
  ERROR:    at KennyAssetViewer.KenneyAssetsPlugin._EnterTree() in E:\Workspace\new-game-project\addons\kenney-assets-helper\scripts\KenneyAssetsPlugin.cs:line 18
  ERROR:    at Godot.Node.InvokeGodotClassMethod(godot_string_name& method, NativeVariantPtrArgs args, godot_variant& ret) in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Generated/GodotObjects/Node.cs:line 2510
  ERROR:    at Godot.EditorPlugin.InvokeGodotClassMethod(godot_string_name& method, NativeVariantPtrArgs args, godot_variant& ret) in /root/godot/modules/mono/glue/GodotSharp/GodotSharpEditor/Generated/GodotObjects/EditorPlugin.cs:line 1498
  ERROR:    at KennyAssetViewer.KenneyAssetsPlugin.InvokeGodotClassMethod(godot_string_name& method, NativeVariantPtrArgs args, godot_variant& ret) in E:\Workspace\new-game-project\.godot\mono\temp\obj\Debug\Godot.SourceGenerators\Godot.SourceGenerators.ScriptMethodsGenerator\KennyAssetViewer.KenneyAssetsPlugin_ScriptMethods.generated.cs:line 50
  ERROR:    at Godot.Bridge.CSharpInstanceBridge.Call(IntPtr godotObjectGCHandle, godot_string_name* method, godot_variant** args, Int32 argCount, godot_variant_call_error* refCallError, godot_variant* ret) in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/Bridge/CSharpInstanceBridge.cs:line 24
```

The directions are not super clear to me but maybe this is related to the order in which I import the assets? Importing seems to take a very, very long time though so I'll have to try again another day.

**Comment by phnix-dev** [comment]
@KrisSiegel Thank you for the logs. I have never used the `dotnet build` command to build a Godot C# project. I always used the [build button](https://docs.godotengine.org/en/stable/tutorials/scripting/c_sharp/c_sharp_basics.html#general-differences-between-c-and-gdscript) on the editor UI.

**Comment by phnix-dev** [comment]
Moreover, I feel like I will need to completely rewrite the code in GDScript to suppress those errors.

**Comment by KrisSiegel** [comment]
Yeah, seems like Godot supports C# add-ons a bit awkwardly but I'm not an expert. Sounds like a good idea. Thanks for looking!
